// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 636341268;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nexora_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Album> crateApiPhotoStoreAddPhotosToAlbum({
    required PhotoStore that,
    required String albumId,
    required List<String> photos,
  });

  Future<void> crateApiPhotoStoreClearPin({required PhotoStore that});

  Future<Album> crateApiPhotoStoreCreateAlbum({
    required PhotoStore that,
    required String name,
  });

  Future<void> crateApiPhotoStoreDeleteAlbum({
    required PhotoStore that,
    required String albumId,
  });

  Future<void> crateApiPhotoStoreDeletePhoto({
    required PhotoStore that,
    required String path,
  });

  Future<void> crateApiPhotoStoreDeleteSecureItem({
    required PhotoStore that,
    required String name,
  });

  Future<void> crateApiPhotoStoreDeleteTrashItem({
    required PhotoStore that,
    required String name,
  });

  Future<void> crateApiPhotoStoreEmptyTrash({required PhotoStore that});

  Future<List<String>> crateApiPhotoStoreFavoritePaths({
    required PhotoStore that,
  });

  Future<List<Photo>> crateApiPhotoStoreGetPhotos({
    required PhotoStore that,
    required List<String> paths,
  });

  Future<List<String>> crateApiPhotoStoreHiddenPaths({
    required PhotoStore that,
  });

  Future<List<Album>> crateApiPhotoStoreListAlbums({required PhotoStore that});

  Future<List<MovedEntry>> crateApiPhotoStoreListSecure({
    required PhotoStore that,
  });

  Future<List<MovedEntry>> crateApiPhotoStoreListTrash({
    required PhotoStore that,
  });

  Future<MovedEntry> crateApiPhotoStoreMoveToSecure({
    required PhotoStore that,
    required String path,
  });

  Future<MovedEntry> crateApiPhotoStoreMoveToTrash({
    required PhotoStore that,
    required String path,
  });

  Future<PhotoStore> crateApiPhotoStoreNew({required String configDir});

  Future<bool> crateApiPhotoStorePinIsSet({required PhotoStore that});

  Future<Album> crateApiPhotoStoreRemovePhotosFromAlbum({
    required PhotoStore that,
    required String albumId,
    required List<String> photos,
  });

  Future<Album> crateApiPhotoStoreRenameAlbum({
    required PhotoStore that,
    required String albumId,
    required String newName,
  });

  Future<void> crateApiPhotoStoreRestoreSecure({
    required PhotoStore that,
    required String name,
  });

  Future<void> crateApiPhotoStoreRestoreTrash({
    required PhotoStore that,
    required String name,
  });

  Future<List<Photo>> crateApiPhotoStoreScanDirectory({
    required PhotoStore that,
    required String root,
  });

  Future<List<Photo>> crateApiPhotoStoreScanSystem({required PhotoStore that});

  Future<List<VideoFile>> crateApiPhotoStoreScanSystemVideos({
    required PhotoStore that,
  });

  Future<List<VideoFile>> crateApiPhotoStoreScanVideos({
    required PhotoStore that,
    required String root,
  });

  Future<void> crateApiPhotoStoreSetFavorite({
    required PhotoStore that,
    required String path,
    required bool isFavorite,
  });

  Future<void> crateApiPhotoStoreSetHidden({
    required PhotoStore that,
    required String path,
    required bool isHidden,
  });

  Future<void> crateApiPhotoStoreSetPin({
    required PhotoStore that,
    required String pin,
  });

  Future<Uint8List?> crateApiPhotoStoreThumbnailBytes({
    required PhotoStore that,
    required String path,
    required int size,
  });

  Future<bool> crateApiPhotoStoreVerifyPin({
    required PhotoStore that,
    required String pin,
  });

  String crateApiGreet({required String name});

  Future<void> crateApiInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PhotoStore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PhotoStore;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PhotoStorePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Album> crateApiPhotoStoreAddPhotosToAlbum({
    required PhotoStore that,
    required String albumId,
    required List<String> photos,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(albumId, serializer);
          sse_encode_list_String(photos, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_album,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreAddPhotosToAlbumConstMeta,
        argValues: [that, albumId, photos],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreAddPhotosToAlbumConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_add_photos_to_album",
        argNames: ["that", "albumId", "photos"],
      );

  @override
  Future<void> crateApiPhotoStoreClearPin({required PhotoStore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreClearPinConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreClearPinConstMeta => const TaskConstMeta(
    debugName: "PhotoStore_clear_pin",
    argNames: ["that"],
  );

  @override
  Future<Album> crateApiPhotoStoreCreateAlbum({
    required PhotoStore that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_album,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreCreateAlbumConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreCreateAlbumConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_create_album",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiPhotoStoreDeleteAlbum({
    required PhotoStore that,
    required String albumId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(albumId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreDeleteAlbumConstMeta,
        argValues: [that, albumId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreDeleteAlbumConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_delete_album",
        argNames: ["that", "albumId"],
      );

  @override
  Future<void> crateApiPhotoStoreDeletePhoto({
    required PhotoStore that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreDeletePhotoConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreDeletePhotoConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_delete_photo",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateApiPhotoStoreDeleteSecureItem({
    required PhotoStore that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreDeleteSecureItemConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreDeleteSecureItemConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_delete_secure_item",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiPhotoStoreDeleteTrashItem({
    required PhotoStore that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreDeleteTrashItemConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreDeleteTrashItemConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_delete_trash_item",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiPhotoStoreEmptyTrash({required PhotoStore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreEmptyTrashConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreEmptyTrashConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_empty_trash",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiPhotoStoreFavoritePaths({
    required PhotoStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreFavoritePathsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreFavoritePathsConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_favorite_paths",
        argNames: ["that"],
      );

  @override
  Future<List<Photo>> crateApiPhotoStoreGetPhotos({
    required PhotoStore that,
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_photo,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreGetPhotosConstMeta,
        argValues: [that, paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreGetPhotosConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_get_photos",
        argNames: ["that", "paths"],
      );

  @override
  Future<List<String>> crateApiPhotoStoreHiddenPaths({
    required PhotoStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreHiddenPathsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreHiddenPathsConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_hidden_paths",
        argNames: ["that"],
      );

  @override
  Future<List<Album>> crateApiPhotoStoreListAlbums({required PhotoStore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_album,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreListAlbumsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreListAlbumsConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_list_albums",
        argNames: ["that"],
      );

  @override
  Future<List<MovedEntry>> crateApiPhotoStoreListSecure({
    required PhotoStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_moved_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreListSecureConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreListSecureConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_list_secure",
        argNames: ["that"],
      );

  @override
  Future<List<MovedEntry>> crateApiPhotoStoreListTrash({
    required PhotoStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_moved_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreListTrashConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreListTrashConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_list_trash",
        argNames: ["that"],
      );

  @override
  Future<MovedEntry> crateApiPhotoStoreMoveToSecure({
    required PhotoStore that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_moved_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreMoveToSecureConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreMoveToSecureConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_move_to_secure",
        argNames: ["that", "path"],
      );

  @override
  Future<MovedEntry> crateApiPhotoStoreMoveToTrash({
    required PhotoStore that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_moved_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreMoveToTrashConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreMoveToTrashConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_move_to_trash",
        argNames: ["that", "path"],
      );

  @override
  Future<PhotoStore> crateApiPhotoStoreNew({required String configDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreNewConstMeta,
        argValues: [configDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreNewConstMeta =>
      const TaskConstMeta(debugName: "PhotoStore_new", argNames: ["configDir"]);

  @override
  Future<bool> crateApiPhotoStorePinIsSet({required PhotoStore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStorePinIsSetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStorePinIsSetConstMeta => const TaskConstMeta(
    debugName: "PhotoStore_pin_is_set",
    argNames: ["that"],
  );

  @override
  Future<Album> crateApiPhotoStoreRemovePhotosFromAlbum({
    required PhotoStore that,
    required String albumId,
    required List<String> photos,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(albumId, serializer);
          sse_encode_list_String(photos, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_album,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreRemovePhotosFromAlbumConstMeta,
        argValues: [that, albumId, photos],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreRemovePhotosFromAlbumConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_remove_photos_from_album",
        argNames: ["that", "albumId", "photos"],
      );

  @override
  Future<Album> crateApiPhotoStoreRenameAlbum({
    required PhotoStore that,
    required String albumId,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(albumId, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_album,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreRenameAlbumConstMeta,
        argValues: [that, albumId, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreRenameAlbumConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_rename_album",
        argNames: ["that", "albumId", "newName"],
      );

  @override
  Future<void> crateApiPhotoStoreRestoreSecure({
    required PhotoStore that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreRestoreSecureConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreRestoreSecureConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_restore_secure",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiPhotoStoreRestoreTrash({
    required PhotoStore that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreRestoreTrashConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreRestoreTrashConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_restore_trash",
        argNames: ["that", "name"],
      );

  @override
  Future<List<Photo>> crateApiPhotoStoreScanDirectory({
    required PhotoStore that,
    required String root,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_photo,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreScanDirectoryConstMeta,
        argValues: [that, root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreScanDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_scan_directory",
        argNames: ["that", "root"],
      );

  @override
  Future<List<Photo>> crateApiPhotoStoreScanSystem({required PhotoStore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_photo,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreScanSystemConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreScanSystemConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_scan_system",
        argNames: ["that"],
      );

  @override
  Future<List<VideoFile>> crateApiPhotoStoreScanSystemVideos({
    required PhotoStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_video_file,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreScanSystemVideosConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreScanSystemVideosConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_scan_system_videos",
        argNames: ["that"],
      );

  @override
  Future<List<VideoFile>> crateApiPhotoStoreScanVideos({
    required PhotoStore that,
    required String root,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_video_file,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreScanVideosConstMeta,
        argValues: [that, root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreScanVideosConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_scan_videos",
        argNames: ["that", "root"],
      );

  @override
  Future<void> crateApiPhotoStoreSetFavorite({
    required PhotoStore that,
    required String path,
    required bool isFavorite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_bool(isFavorite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreSetFavoriteConstMeta,
        argValues: [that, path, isFavorite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreSetFavoriteConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_set_favorite",
        argNames: ["that", "path", "isFavorite"],
      );

  @override
  Future<void> crateApiPhotoStoreSetHidden({
    required PhotoStore that,
    required String path,
    required bool isHidden,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_bool(isHidden, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreSetHiddenConstMeta,
        argValues: [that, path, isHidden],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreSetHiddenConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_set_hidden",
        argNames: ["that", "path", "isHidden"],
      );

  @override
  Future<void> crateApiPhotoStoreSetPin({
    required PhotoStore that,
    required String pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreSetPinConstMeta,
        argValues: [that, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreSetPinConstMeta => const TaskConstMeta(
    debugName: "PhotoStore_set_pin",
    argNames: ["that", "pin"],
  );

  @override
  Future<Uint8List?> crateApiPhotoStoreThumbnailBytes({
    required PhotoStore that,
    required String path,
    required int size,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_u_32(size, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreThumbnailBytesConstMeta,
        argValues: [that, path, size],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreThumbnailBytesConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_thumbnail_bytes",
        argNames: ["that", "path", "size"],
      );

  @override
  Future<bool> crateApiPhotoStoreVerifyPin({
    required PhotoStore that,
    required String pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
            that,
            serializer,
          );
          sse_encode_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotoStoreVerifyPinConstMeta,
        argValues: [that, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotoStoreVerifyPinConstMeta =>
      const TaskConstMeta(
        debugName: "PhotoStore_verify_pin",
        argNames: ["that", "pin"],
      );

  @override
  String crateApiGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PhotoStore => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PhotoStore => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore;

  @protected
  PhotoStore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PhotoStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PhotoStore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PhotoStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PhotoStore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PhotoStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Album dco_decode_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Album(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      photoPaths: dco_decode_list_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Album> dco_decode_list_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_album).toList();
  }

  @protected
  List<MovedEntry> dco_decode_list_moved_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_moved_entry).toList();
  }

  @protected
  List<Photo> dco_decode_list_photo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_photo).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VideoFile> dco_decode_list_video_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_video_file).toList();
  }

  @protected
  MovedEntry dco_decode_moved_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MovedEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      original: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  Photo dco_decode_photo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return Photo(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      extension_: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
      width: dco_decode_u_32(arr[4]),
      height: dco_decode_u_32(arr[5]),
      takenAt: dco_decode_opt_String(arr[6]),
      isFavorite: dco_decode_bool(arr[7]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoFile dco_decode_video_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VideoFile(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      extension_: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  PhotoStore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PhotoStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PhotoStore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PhotoStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PhotoStore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PhotoStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Album sse_decode_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_photoPaths = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return Album(
      id: var_id,
      name: var_name,
      photoPaths: var_photoPaths,
      createdAt: var_createdAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Album>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_album(deserializer));
    }
    return ans_;
  }

  @protected
  List<MovedEntry> sse_decode_list_moved_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MovedEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_moved_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<Photo> sse_decode_list_photo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Photo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_photo(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VideoFile> sse_decode_list_video_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VideoFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_video_file(deserializer));
    }
    return ans_;
  }

  @protected
  MovedEntry sse_decode_moved_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_original = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    return MovedEntry(
      name: var_name,
      path: var_path,
      original: var_original,
      sizeBytes: var_sizeBytes,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Photo sse_decode_photo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_takenAt = sse_decode_opt_String(deserializer);
    var var_isFavorite = sse_decode_bool(deserializer);
    return Photo(
      path: var_path,
      name: var_name,
      extension_: var_extension_,
      sizeBytes: var_sizeBytes,
      width: var_width,
      height: var_height,
      takenAt: var_takenAt,
      isFavorite: var_isFavorite,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoFile sse_decode_video_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    return VideoFile(
      path: var_path,
      name: var_name,
      extension_: var_extension_,
      sizeBytes: var_sizeBytes,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    PhotoStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PhotoStoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    PhotoStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PhotoStoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPhotoStore(
    PhotoStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PhotoStoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_album(Album self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.photoPaths, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_album(item, serializer);
    }
  }

  @protected
  void sse_encode_list_moved_entry(
    List<MovedEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_moved_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_photo(List<Photo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_photo(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_video_file(
    List<VideoFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_video_file(item, serializer);
    }
  }

  @protected
  void sse_encode_moved_entry(MovedEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.original, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_photo(Photo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.extension_, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_opt_String(self.takenAt, serializer);
    sse_encode_bool(self.isFavorite, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_file(VideoFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.extension_, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class PhotoStoreImpl extends RustOpaque implements PhotoStore {
  // Not to be used by end users
  PhotoStoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PhotoStoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PhotoStore,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PhotoStore,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PhotoStorePtr,
  );

  Future<Album> addPhotosToAlbum({
    required String albumId,
    required List<String> photos,
  }) => RustLib.instance.api.crateApiPhotoStoreAddPhotosToAlbum(
    that: this,
    albumId: albumId,
    photos: photos,
  );

  Future<void> clearPin() =>
      RustLib.instance.api.crateApiPhotoStoreClearPin(that: this);

  Future<Album> createAlbum({required String name}) => RustLib.instance.api
      .crateApiPhotoStoreCreateAlbum(that: this, name: name);

  Future<void> deleteAlbum({required String albumId}) => RustLib.instance.api
      .crateApiPhotoStoreDeleteAlbum(that: this, albumId: albumId);

  Future<void> deletePhoto({required String path}) => RustLib.instance.api
      .crateApiPhotoStoreDeletePhoto(that: this, path: path);

  Future<void> deleteSecureItem({required String name}) => RustLib.instance.api
      .crateApiPhotoStoreDeleteSecureItem(that: this, name: name);

  Future<void> deleteTrashItem({required String name}) => RustLib.instance.api
      .crateApiPhotoStoreDeleteTrashItem(that: this, name: name);

  Future<void> emptyTrash() =>
      RustLib.instance.api.crateApiPhotoStoreEmptyTrash(that: this);

  Future<List<String>> favoritePaths() =>
      RustLib.instance.api.crateApiPhotoStoreFavoritePaths(that: this);

  Future<List<Photo>> getPhotos({required List<String> paths}) => RustLib
      .instance
      .api
      .crateApiPhotoStoreGetPhotos(that: this, paths: paths);

  Future<List<String>> hiddenPaths() =>
      RustLib.instance.api.crateApiPhotoStoreHiddenPaths(that: this);

  Future<List<Album>> listAlbums() =>
      RustLib.instance.api.crateApiPhotoStoreListAlbums(that: this);

  Future<List<MovedEntry>> listSecure() =>
      RustLib.instance.api.crateApiPhotoStoreListSecure(that: this);

  Future<List<MovedEntry>> listTrash() =>
      RustLib.instance.api.crateApiPhotoStoreListTrash(that: this);

  Future<MovedEntry> moveToSecure({required String path}) => RustLib
      .instance
      .api
      .crateApiPhotoStoreMoveToSecure(that: this, path: path);

  Future<MovedEntry> moveToTrash({required String path}) => RustLib.instance.api
      .crateApiPhotoStoreMoveToTrash(that: this, path: path);

  Future<bool> pinIsSet() =>
      RustLib.instance.api.crateApiPhotoStorePinIsSet(that: this);

  Future<Album> removePhotosFromAlbum({
    required String albumId,
    required List<String> photos,
  }) => RustLib.instance.api.crateApiPhotoStoreRemovePhotosFromAlbum(
    that: this,
    albumId: albumId,
    photos: photos,
  );

  Future<Album> renameAlbum({
    required String albumId,
    required String newName,
  }) => RustLib.instance.api.crateApiPhotoStoreRenameAlbum(
    that: this,
    albumId: albumId,
    newName: newName,
  );

  Future<void> restoreSecure({required String name}) => RustLib.instance.api
      .crateApiPhotoStoreRestoreSecure(that: this, name: name);

  Future<void> restoreTrash({required String name}) => RustLib.instance.api
      .crateApiPhotoStoreRestoreTrash(that: this, name: name);

  Future<List<Photo>> scanDirectory({required String root}) => RustLib
      .instance
      .api
      .crateApiPhotoStoreScanDirectory(that: this, root: root);

  /// Escanea todas las fotos del equipo (desde $HOME), saltando carpetas
  /// ocultas y de ruido, y excluyendo la configuración/papelera/segura.
  Future<List<Photo>> scanSystem() =>
      RustLib.instance.api.crateApiPhotoStoreScanSystem(that: this);

  Future<List<VideoFile>> scanSystemVideos() =>
      RustLib.instance.api.crateApiPhotoStoreScanSystemVideos(that: this);

  Future<List<VideoFile>> scanVideos({required String root}) =>
      RustLib.instance.api.crateApiPhotoStoreScanVideos(that: this, root: root);

  Future<void> setFavorite({required String path, required bool isFavorite}) =>
      RustLib.instance.api.crateApiPhotoStoreSetFavorite(
        that: this,
        path: path,
        isFavorite: isFavorite,
      );

  Future<void> setHidden({required String path, required bool isHidden}) =>
      RustLib.instance.api.crateApiPhotoStoreSetHidden(
        that: this,
        path: path,
        isHidden: isHidden,
      );

  Future<void> setPin({required String pin}) =>
      RustLib.instance.api.crateApiPhotoStoreSetPin(that: this, pin: pin);

  Future<Uint8List?> thumbnailBytes({
    required String path,
    required int size,
  }) => RustLib.instance.api.crateApiPhotoStoreThumbnailBytes(
    that: this,
    path: path,
    size: size,
  );

  Future<bool> verifyPin({required String pin}) =>
      RustLib.instance.api.crateApiPhotoStoreVerifyPin(that: this, pin: pin);
}
